//LOCALHOST
### Get all contacts
GET http://localhost:3000/contacts

### Get contact by id
GET http://localhost:3000/contacts/681c84c7c39d7ac977098a80 



### Create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{

"firstName": "Celia",
"lastName": "Cruz",
"email": "BembaColora@mail.com",
"favoriteColor": "white",
"birthday": "1975-10-01T00:00:00.000Z"

}


### Put contact
PUT http://localhost:3000/contacts/681c84c7c39d7ac977098a80 HTTP/1.1
content-type: application/json

{

"firstName": "Hector",
"lastName": "Lavoe",
"email": "HolaMiGente@mail.com",
"favoriteColor": "green",
"birthday": "1975-10-01T00:00:00.000Z"

}


### Delete contact
DELETE http://localhost:3000/contacts/682323f0061c611a9f1c594f HTTP/1.1
